# GitHub Actions workflow для автоматической компиляции llama.cpp
# 
# Этот workflow компилирует llama.cpp для Android и iOS при каждом push
# и создает артефакты, которые можно скачать

name: Build llama.cpp for AKA

on:
  workflow_dispatch: # Ручной запуск
  push:
    paths:
      - 'scripts/build_llama_*.sh'
      - '.github/workflows/setup_llama_github_actions.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Android NDK
        uses: android-actions/setup-android-ndk@v2
        with:
          ndk-version: '25.2.9519653'
      
      - name: Build for ARM64
        run: |
          chmod +x scripts/build_llama_android.sh
          export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
          bash scripts/build_llama_android.sh
      
      - name: Upload Android libraries
        uses: actions/upload-artifact@v3
        with:
          name: llama-android-libs
          path: android/app/src/main/jniLibs/
          retention-days: 30

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build for iOS
        run: |
          chmod +x scripts/build_llama_ios.sh
          bash scripts/build_llama_ios.sh
      
      - name: Upload iOS framework
        uses: actions/upload-artifact@v3
        with:
          name: llama-ios-framework
          path: ios/Frameworks/llama.framework/
          retention-days: 30

  download-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download model
        run: |
          chmod +x scripts/download_model.sh
          bash scripts/download_model.sh
      
      - name: Upload model
        uses: actions/upload-artifact@v3
        with:
          name: llama-model-v1
          path: assets/aka/models/model_v1.bin
          retention-days: 7 # Модель большая, храним недолго
